const RAW_BASE="https://raw.githubusercontent.com/bjo163/rocksoul-assets/main/";
const REGISTRY_URL="/dist/assets.json";
const CATALOG_URL="/showcase/catalog.json";
let registry=null,catalog=null,selectedCategory="All",query="",view="grid",currentEntry=null;
const $=(selector)=>document.querySelector(selector);
const $$=(selector)=>[...document.querySelectorAll(selector)];
const grid=$("#packGrid"),filters=$("#filters"),search=$("#searchInput"),dialog=$("#assetDialog");
const categoryOrder=["Foundations","Core","Investigation","Workflow","Identity","Media","System"];
const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)");
const assetUrl=(path)=>path.startsWith("http")?path:RAW_BASE+path.replace(/^\//,"");
const prettify=(id)=>id.replaceAll("-"," ").replace(/\b\w/g,(m)=>m.toUpperCase());
const escapeHtml=(value)=>String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function metaFor(id){return catalog?.entries?.[id]??{label:prettify(id),category:"System",description:"MoonWitness delivery collection."};}
function registryEntry(id){if(registry?.packs?.[id])return{id,kind:"pack",...registry.packs[id]};if(registry?.collections?.[id])return{id,kind:"foundation",...registry.collections[id]};return null;}
function allEntries(){return Object.keys(catalog?.entries??{}).map(registryEntry).filter(Boolean);}
function flattenPng(png){const out=[];for(const [name,value] of Object.entries(png??{})){if(typeof value==="string")out.push({name,path:value});else if(value&&typeof value==="object"){for(const [size,path] of Object.entries(value))out.push({name:name+" @"+size,path});}}return out;}
function formatForPath(path,id){const lower=path.toLowerCase();if(id==="runtime-motion"&&lower.includes("/png/")&&lower.endsWith(".png"))return"APNG";if(lower.includes("/lottie/")&&lower.endsWith(".json"))return"LOTTIE";if(lower.endsWith(".svg"))return"SVG";if(lower.endsWith(".png"))return"PNG";if(lower.endsWith(".ico"))return"ICO";if(lower.endsWith(".webm"))return"WEBM";if(lower.endsWith(".wav"))return"WAV";if(lower.endsWith(".ogg"))return"OGG";if(lower.endsWith(".json"))return"JSON";if(lower.endsWith(".ts"))return"TS";if(lower.endsWith(".css"))return"CSS";return path.split(".").pop()?.toUpperCase()??"FILE";}
function fileItems(entry){const seen=new Set(),items=[];const push=(path,name=null,artifact=false)=>{if(!path||seen.has(path))return;seen.add(path);items.push({name:name??path.split("/").pop()?.replace(/\.[^.]+$/,"")??path,path,format:formatForPath(path,entry.id),artifact});};for(const path of entry.files??[])push(path);for(const [name,path] of Object.entries(entry.artifacts??{}))push(path,name,true);const order=["SVG","PNG","APNG","ICO","WEBM","LOTTIE","WAV","OGG","JSON","TS","CSS"];return items.sort((a,b)=>(order.indexOf(a.format)-order.indexOf(b.format))||a.path.localeCompare(b.path));}
function formatsFor(entry){return[...new Set(fileItems(entry).map((item)=>item.format))];}
function previewCandidates(entry){const svgs=Object.values(entry.svg??{});if(svgs.length)return svgs.slice(0,3);const pngs=flattenPng(entry.png).map((item)=>item.path);if(pngs.length)return pngs.slice(0,3);return[];}
function entryPreview(entry){const previews=previewCandidates(entry);if(previews.length===1)return'<img loading="lazy" src="'+assetUrl(previews[0])+'" alt="" />';if(previews.length>1)return'<div class="preview-icon-set">'+previews.map((path)=>'<img loading="lazy" src="'+assetUrl(path)+'" alt="" />').join("")+'</div>';const formats=formatsFor(entry);if(formats.includes("WAV")||formats.includes("OGG"))return'<div class="preview-fallback">∿</div>';if(entry.id==="developer-distribution")return'<div class="preview-fallback">{ }</div>';return'<div class="preview-fallback">MW</div>';}
function createCard(entry,index,total){const meta=metaFor(entry.id),formats=formatsFor(entry),files=fileItems(entry),article=document.createElement("article");article.className="pack-card";article.tabIndex=0;article.dataset.id=entry.id;article.dataset.category=meta.category;article.innerHTML='<div class="pack-preview">'+entryPreview(entry)+'</div><div class="pack-content"><div class="pack-index"><span class="pack-number">'+String(index+1).padStart(2,"0")+' / '+String(total).padStart(2,"0")+'</span><span class="pack-category">'+escapeHtml(meta.category)+'</span></div><div><h3 class="pack-title">'+escapeHtml(meta.label)+'</h3><p class="pack-description">'+escapeHtml(meta.description)+'</p></div><div class="pack-footer"><span class="pack-count">'+entry.count+' canonical<span class="pack-file-count">'+files.length+' reachable files</span></span><div class="format-row">'+formats.slice(0,4).map((format)=>'<span class="format-badge">'+format+'</span>').join("")+'</div></div></div>';article.addEventListener("click",()=>openEntry(entry.id));article.addEventListener("keydown",(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();openEntry(entry.id);}});return article;}
function categoryEntries(category){return allEntries().filter((entry)=>metaFor(entry.id).category===category);}
function renderCapabilities(){for(const category of categoryOrder){const entries=categoryEntries(category),fileCount=entries.reduce((sum,entry)=>sum+fileItems(entry).length,0),countNode=document.querySelector('[data-count-category="'+category+'"]'),previewNode=document.querySelector('[data-preview-category="'+category+'"]');if(countNode)countNode.textContent=entries.length+" collections · "+fileCount+" files";if(previewNode&&entries[0]){const candidates=previewCandidates(entries[0]);previewNode.innerHTML=candidates[0]?'<img loading="lazy" src="'+assetUrl(candidates[0])+'" alt="" />':'<span class="preview-fallback">'+entries.length+'</span>';}}}
function renderFilters(){const used=new Set(allEntries().map((entry)=>metaFor(entry.id).category)),categories=["All",...categoryOrder.filter((category)=>used.has(category))];filters.innerHTML="";for(const category of categories){const button=document.createElement("button");button.type="button";button.className="filter-button"+(category===selectedCategory?" active":"");button.textContent=category;button.setAttribute("aria-pressed",String(category===selectedCategory));button.onclick=()=>setCategory(category,true);filters.appendChild(button);}}
function setCategory(category,scroll=false){selectedCategory=category;renderFilters();renderExplorer();syncUrl();if(scroll)$("#explorer").scrollIntoView({behavior:reducedMotion.matches?"auto":"smooth",block:"start"});}
function matches(entry){const meta=metaFor(entry.id);if(selectedCategory!=="All"&&meta.category!==selectedCategory)return false;if(!query)return true;const hay=[entry.id,meta.label,meta.category,meta.description,...fileItems(entry).flatMap((item)=>[item.name,item.path,item.format])].join(" ").toLowerCase();return hay.includes(query);}
function renderExplorer(){if(!registry||!catalog)return;grid.classList.toggle("compact",view==="compact");grid.innerHTML="";const entries=allEntries();let shown=0;entries.forEach((entry,index)=>{if(matches(entry)){grid.appendChild(createCard(entry,index,entries.length));shown++;}});$("#resultCount").textContent=shown+" of "+entries.length+" collections · "+registry.coverage.deliveryFiles+" total delivery files";$("#emptyResults").hidden=shown!==0;}
function syncUrl(){const url=new URL(location.href);if(query)url.searchParams.set("q",query);else url.searchParams.delete("q");if(selectedCategory!=="All")url.searchParams.set("category",selectedCategory);else url.searchParams.delete("category");history.replaceState(null,"",url.pathname+url.search+url.hash);}
async function previewAsset(item){const box=$("#dialogPreview"),url=assetUrl(item.path),label=escapeHtml(prettify(item.name));if(["SVG","PNG","APNG","ICO"].includes(item.format)){box.innerHTML='<img src="'+url+'" alt="'+label+' preview" />';return;}if(item.format==="WEBM"){box.innerHTML='<video src="'+url+'" controls'+(reducedMotion.matches?"":" autoplay")+' loop muted playsinline aria-label="'+label+' preview"></video>';return;}if(["WAV","OGG"].includes(item.format)){box.innerHTML='<div class="preview-audio"><span>∿ AUDIO</span><audio src="'+url+'" controls preload="metadata"></audio><small>'+escapeHtml(item.path)+'</small></div>';return;}if(["LOTTIE","JSON","TS","CSS"].includes(item.format)){box.innerHTML='<pre class="text-preview">Loading '+item.format+'…</pre>';try{const response=await fetch(url),text=await response.text(),clipped=text.length>16000?text.slice(0,16000)+"\n\n… preview truncated …":text;box.innerHTML='<pre class="text-preview">'+escapeHtml(clipped)+'</pre>';}catch{box.innerHTML='<pre class="text-preview">Preview unavailable. Use “Open raw asset”.</pre>';}return;}box.innerHTML='<div class="preview-fallback">'+escapeHtml(item.format)+'</div>';}
function openEntry(id){const entry=registryEntry(id);if(!entry)return;currentEntry=entry;const meta=metaFor(id),items=fileItems(entry);$("#dialogCategory").textContent=meta.category+" / "+(entry.kind==="foundation"?"Foundation collection":"Asset pack");$("#dialogTitle").textContent=meta.label;$("#dialogMeta").innerHTML=entry.count+' canonical assets · <span class="dialog-file-count">'+items.length+' reachable files</span> · '+formatsFor(entry).join(" · ");$("#dialogManifest").href=assetUrl(entry.manifest);$("#dialogSearch").value="";renderAssetList("");const first=items.find((item)=>item.format==="SVG")??items.find((item)=>item.format==="PNG")??items[0];if(first)previewAsset(first);dialog.showModal();const url=new URL(location.href);url.hash="pack="+encodeURIComponent(id);history.replaceState(null,"",url.pathname+url.search+url.hash);}
function renderAssetList(filter){if(!currentEntry)return;const q=filter.trim().toLowerCase(),list=$("#assetList"),items=fileItems(currentEntry).filter((item)=>!q||[item.name,item.path,item.format].join(" ").toLowerCase().includes(q));list.innerHTML="";for(const item of items){const row=document.createElement("div");row.className="asset-row";row.dataset.format=item.format;const visual=["SVG","PNG","APNG","ICO"].includes(item.format),thumb=visual?'<img loading="lazy" src="'+assetUrl(item.path)+'" alt="" />':'<span class="asset-format">'+item.format+'</span>';row.innerHTML='<div class="asset-thumb">'+thumb+'</div><div class="asset-name"><strong>'+escapeHtml(prettify(item.name))+' <span class="asset-format">'+item.format+'</span></strong><span>'+escapeHtml(item.path)+'</span></div><div class="asset-actions"><button class="tiny-button" data-copy="'+escapeHtml(item.path)+'" title="Copy asset path" aria-label="Copy '+escapeHtml(item.path)+'">⧉</button><a class="tiny-button" href="'+assetUrl(item.path)+'" target="_blank" rel="noreferrer" title="Open raw asset" aria-label="Open raw asset">↗</a></div>';row.addEventListener("click",(event)=>{if(event.target.closest("button,a"))return;previewAsset(item);});list.appendChild(row);}list.querySelectorAll("[data-copy]").forEach((button)=>{button.onclick=async(event)=>{event.stopPropagation();await navigator.clipboard.writeText(button.dataset.copy);toast("Path copied");};});}
let toastTimer;function toast(message){const node=$("#toast");node.textContent=message;node.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove("show"),1400);}
function setView(next){view=next;$$(".view-button").forEach((button)=>{const active=button.dataset.view===view;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active));});renderExplorer();}
async function init(){try{const urlState=new URL(location.href);query=(urlState.searchParams.get("q")??"").trim().toLowerCase();selectedCategory=urlState.searchParams.get("category")??"All";search.value=urlState.searchParams.get("q")??"";const [registryResponse,catalogResponse]=await Promise.all([fetch(REGISTRY_URL),fetch(CATALOG_URL)]);if(!registryResponse.ok)throw new Error("Registry unavailable");if(!catalogResponse.ok)throw new Error("Showcase catalog unavailable");registry=await registryResponse.json();catalog=await catalogResponse.json();$("#statPacks").textContent=registry.coverage.packFamilies;$("#statCollections").textContent=registry.coverage.showcaseCollections;$("#statAssets").textContent=registry.coverage.deliveryFiles.toLocaleString();$("#statCoverage").textContent=registry.coverage.coveragePercent+"%";$("#statVersion").textContent="v"+registry.version;$("#registryState").innerHTML='<span class="status-dot"></span> '+registry.coverage.indexedDeliveryFiles+'/'+registry.coverage.deliveryFiles+' files indexed';if(selectedCategory!=="All"&&!categoryOrder.includes(selectedCategory))selectedCategory="All";renderCapabilities();renderFilters();renderExplorer();const hash=new URLSearchParams(location.hash.replace(/^#/,"")),id=hash.get("pack");if(id&&registryEntry(id))openEntry(id);}catch(error){$("#registryState").textContent="Registry unavailable";$("#resultCount").textContent="Unable to load complete asset registry";grid.innerHTML='<div class="empty-results"><strong>Registry could not be loaded.</strong><p>'+escapeHtml(error.message)+'</p></div>';}}
search.addEventListener("input",()=>{query=search.value.trim().toLowerCase();renderExplorer();syncUrl();});
$("#resetSearch").onclick=()=>{search.value="";query="";selectedCategory="All";renderFilters();renderExplorer();syncUrl();};
$$(".view-button").forEach((button)=>button.onclick=()=>setView(button.dataset.view));
$$("[data-category]").forEach((button)=>button.onclick=()=>setCategory(button.dataset.category,true));
$$("[data-open-pack]").forEach((link)=>link.addEventListener("click",(event)=>{event.preventDefault();openEntry(link.dataset.openPack);}));
$("#copyCode").onclick=async()=>{const text='import { assets } from "./dist/assets";\n\nassets.packs["evidence-media"].svg["bounding-box"];\nassets.packs["correlation-semantics"].svg["edge-supports"];\nassets.packs["badge-status"].svg.verified;\nassets.packs["persona-avatar"].png.researcher["64"];';await navigator.clipboard.writeText(text);toast("Example copied");};
$("#themeToggle").onclick=()=>{const root=document.documentElement,next=root.dataset.theme==="dark"?"light":"dark";root.dataset.theme=next;localStorage.setItem("mw-theme",next);};
const savedTheme=localStorage.getItem("mw-theme");if(savedTheme)document.documentElement.dataset.theme=savedTheme;
$("#dialogClose").onclick=()=>dialog.close();
dialog.addEventListener("click",(event)=>{if(event.target===dialog)dialog.close();});
dialog.addEventListener("close",()=>{currentEntry=null;const url=new URL(location.href);if(url.hash.startsWith("#pack=")){url.hash="";history.replaceState(null,"",url.pathname+url.search);}});
$("#dialogSearch").addEventListener("input",(event)=>renderAssetList(event.target.value));
window.addEventListener("keydown",(event)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();if(!dialog.open)search.focus();}});
window.addEventListener("hashchange",()=>{const hash=new URLSearchParams(location.hash.replace(/^#/,"")),id=hash.get("pack");if(id&&registryEntry(id)&&(!dialog.open||currentEntry?.id!==id))openEntry(id);});
init();